name: Tests
on: [push, pull_request]
jobs:
  test-node-14:
    name: Node.js v14
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: make node_modules
      - name: Run checks
        run: make check
      - name: Run tests
        run: make ci-test
  test-node-16:
    name: Node.js v16
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: make node_modules
      - name: Run checks
        run: make check
      - name: Run tests
        run: make ci-test
